version: '3.8'
services:

  catalog-service:
    depends_on:
     - catalog-postgres
     - config-service
    image: ghcr.io/polarsophia/catalog-service:latest
    container_name: catalog-service
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgres:5432/catalog
    
  config-service:
    image: ghcr.io/polarsophia/config-service:latest
    container_name: config-service
    ports:
      - 8888:8888
      - 5006:5006
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5006

  catalog-postgres:
    image: postgres
    container_name: catalog-postgres
    environment:
      - POSTGRES_USER=acdevs
      - POSTGRES_PASSWORD=4444
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"