version: '3.8'
services:

  catalog-service:
    depends_on:
     - catalog-postgres
    image: ghcr.io/acdevz/catalog-service
    container_name: catalog-service
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgres:5432/catalog
    
  catalog-postgres:
    image: postgres
    container_name: catalog-postgres
    environment:
      - POSTGRES_USER=acdevs
      - POSTGRES_PASSWORD=4444
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"