services:
  edge-service:
    depends_on:
      - polar-redis
      - config-service
    image: ghcr.io/polarsophia/edge-service:latest
    container_name: edge-service
    ports:
      - 9000:9000
    environment:
      - SPRING_DATA_REDIS_HOST=polar-redis
      - SPRING_DATA_REDIS_PORT=6379
      - CATALOG_SERVICE_URL=http://catalog-service:8080
      - ORDER_SERVICE_URL=http://order-service:8090
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  catalog-service:
    depends_on:
     - polar-postgres
     - config-service
    image: ghcr.io/polarsophia/catalog-service:latest
    container_name: catalog-service
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=testData

  order-service:
    depends_on:
      - polar-postgres
      - config-service
    image: ghcr.io/polarsophia/order-service:latest
    container_name: order-service
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/order
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:8080


  config-service:
    image: ghcr.io/polarsophia/config-service:latest
    container_name: config-service
    ports:
      - 8888:8888
      - 5006:5006
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5006

  polar-postgres:
    image: postgres:15
    container_name: polar-postgres
    restart: always
    environment:
      - POSTGRES_USER=acdevs
      - POSTGRES_PASSWORD=4444
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  polar-redis:
    image: "redis:7.0"
    container_name: polar-redis
    restart: always
    ports:
      - 6379:6379
