apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: catalog-postgres
data:
  init.sql: |
    CREATE DATABASE catalog;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-postgres
  labels:
    db: catalog-postgres
spec:
  selector:
    matchLabels:
      db: catalog-postgres
  template:
    metadata:
      labels:
        db: catalog-postgres
    spec:
      containers:
        - name: catalog-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: acdevs
            - name: POSTGRES_PASSWORD
              value: '4444'
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-postgres
  labels:
    db: catalog-postgres
spec:
  type: ClusterIP
  selector:
    db: catalog-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432